# Generated by Django 4.2.8 on 2024-01-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ussername', models.CharField(max_length=32)),
                ('password1', models.CharField(max_length=32)),
                ('password2', models.CharField(max_length=32)),
            ],
        ),
    ]
