version: "3.9"
services:
  mycontainer1:
    build: .
    ports: 
      - "3000:3000"
    links: 
      - mycontainer2
  mycontainer2:
    image: mongo
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=drtino
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo-data: /data/db
  
volumes:
  mongo-data: