# Generated by Django 4.2.7 on 2023-12-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0003_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coments',
            new_name='Coment',
        ),
    ]
