BEGIN TRANSACTION;

UPDATE MONEY SET AMOUNT = AMOUNT - 100 WHERE id = 3;
UPDATE MONEY SET AMOUNT = AMOUNT + 100 WHERE id = 1;

COMMIT;

--

BEGIN TRANSACTION;

UPDATE MONEY SET AMOUNT = AMOUNT - 100 WHERE id = 3;
UPDATE MONEY SET AMOUNT = AMOUNT + 100 WHERE id = 1;

ROLLBACK;